version: '2'
services:
  issue-it.db:
    image: postgres
  issue-it.web:
    build: .
    environment:
      - DB_USERNAME=postgres
      - DB_HOST=db
    command: bundle exec rails s -p 5001 -b '0.0.0.0'
    volumes:
      - .:/issue-it
    ports:
      - "5001:5001"
    links:
      - issue-it.db:db
    depends_on:
      - issue-it.db
